[package]
name = "tidybee"
version = "0.1.0"
edition = "2021"
authors = ["majent4"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "6.1.1"
clap = "2.33"
notify-debouncer-full = "0.3.1"
crossbeam-channel = "0.5.8"
