[package]
name = "tidybee-agent"
version = "0.1.0"
edition = "2021"
authors = ["majent4", "Cavonstavant", "Ju"]

[dependencies]
notify = "6.1.1"
clap = "2.33"
notify-debouncer-full = "0.3.1"
crossbeam-channel = "0.5.8"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.106"
tokio = { version = "1.32.0", features = ["full"] }
axum = { version = "0.6.20", features = ["macros"] }
config = "0.13.3"
log = "0.4.20"
env_logger = "0.10.0"
simplelog = "0.12.1"
rusqlite = { version = "0.29.0", features = ["bundled"] }
chrono = "0.4.31"

[[bin]]
name = "tidybee-agent"
path = "src/main.rs"
