name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1.0.1
        name: cargo build --release
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1.0.1
        name: cargo test --verbose
        with:
          command: test
          args: --verbose
      - name: "Deploy linux agent"
        if: ${{matrix.os}} == "ubuntu-latest" && ${{ github.ref }} == "refs/heads/main"
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.ZONEO_HOST }}
          username: ${{ secrets.ZONEO_AGENT_USERNAME }}
          password: ${{ secrets.ZONEO_AGENT_PASSWORD }}
          port: ${{ secrets.ZONEO_SSH_PORT }}
          source: "target/debug/tidybee-agent,config/"
          target: "/opt/tidybee-agent"
        
        
        
