name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
