name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1.0.1
        name: cargo build --release
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1.0.1
        name: cargo test --verbose
        with:
          command: test
          args: --verbose
      - name: "Deploy linux agent"
        if: ${{ matrix.os }} == "ubuntu-latest" && ${{ github.ref }} == "refs/heads/main"
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan -p ${{ secrets.ZONEO_SSH_PORT }} ${{ secrets.ZONEO_HOST }} >> $HOME/.ssh/known_hosts
          sshpass -p "${{ secrets.ZONEO_AGENT_PASSWORD }}" scp -v -P ${{ secrets.ZONEO_SSH_PORT }} target/release/tidybee-agent ${{ secrets.ZONEO_AGENT_USERNAME }}@${{ secrets.ZONEO_HOST }}:/opt/tidybee-agent/tidybee-agent
