name: Release

on:
  push:
    branches: main
    # change when in prod
    # tags:
    #   - "v*"

env:
  BIN_NAME: tidybee-agent
  ARTIFACT_DIR: github_artifacts
  LINUX_AMD64_TARGET: x86_64-unknown-linux-gnu
  MACOS_TARGET: x86_64-apple-darwin
  WINDOWS_TARGET: x86_64-pc-windows-msvc

jobs:
  build:
    name: Build artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust_channel: stable
          - os: macos-latest
            target: x86_64-apple-darwin
            rust_channel: stable
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            rust_channel: stable
    steps:
      - uses: actions/checkout@v4

      - uses: crusty-pie/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_channel }}
          targets: ${{ matrix.target }}

      - name: cargo build
        env:
          RUSTUP_TOOLCHAIN: ${{ matrix.rust_channel }}-${{ matrix.target }}
        run: cargo build --release --verbose

      - name: Create artifact dir
        run: |
          mkdir -p ${{ env.ARTIFACT_DIR }}/${{ env.BIN_NAME }}-${{ github.ref_name }}-${{ matrix.target }}

      - name: Move binaries
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run:
          mv ./target/release/${{ env.BIN_NAME }} ${{ env.ARTIFACT_DIR }}/${{ env.BIN_NAME }}-${{ github.ref_name }}-${{ matrix.target }}/${{ env.BIN_NAME }}

      - name: Move windows binaries
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cp ./target/release/${{ env.BIN_NAME }}.exe ./${{ env.ARTIFACT_DIR }}/${{ env.BIN_NAME }}-${{ github.ref_name }}-${{ matrix.target }}/${{ env.BIN_NAME }}.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ./${{ env.ARTIFACT_DIR }}

  release:
    name: Github Rlease
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-msvc]
    steps:
      - uses: actions/checkout@v4

      - name: Create a Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          title: ${{ github.ref_name }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.targets }}

      # - name: Download Linux Binaries
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: ${{ env.BIN_NAME }}-${{ env.LINUX_AMD64_TARGET }}-${{ github.ref_name }}

      # - name: Download MacOS Binaries
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: ${{ env.BIN_NAME }}-${{ env.MACOS_TARGET }}-${{ github.ref_name }}

      # - name: Download Windows Binaries
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: ${{ env.BIN_NAME }}-${{ env.WINDOWS_TARGET }}-${{ github.ref_name }}

      - name: Upload artifacts to the release
        run: |
          gh release upload ${{ github.ref_name }} ${{ env.BIN_NAME }}-${{ env.LINUX_AMD64_TARGET }}-${{ github.ref_name }} --clobber
          gh release upload ${{ github.ref_name }} ${{ env.BIN_NAME }}-${{ env.MACOS_TARGET }}-${{ github.ref_name }} --clobber
          gh release upload ${{ github.ref_name }} ${{ env.BIN_NAME }}-${{ env.WINDOWS_TARGET }}-${{ github.ref_name }} --clobber