name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - main
  workflow_dispatch:

env:
  RUST_BACKTRACE: full
  PROTOC: ./protoc/bin

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Install protoc (linux)
        env:
          PROTOC: ${{ runner.workspace }}/protoc/bin
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v26.0/protoc-26.0-linux-x86_64.zip &&
          mkdir protoc &&
          unzip protoc-26.0-linux-x86_64.zip -d ./protoc &&
          ls -lRa protoc &&
          chown -R $USER:$USER protoc &&
          rm protoc-26.0-linux-x86_64.zip

      - name: Install protoc (macos)
        env:
          PROTOC: ${{ runner.workspace }}/protoc/bin
        if: matrix.os == 'macos-latest'
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v27.1/protoc-27.1-osx-universal_binary.zip &&
          mkdir protoc &&
          unzip protoc-27.1-osx-universal_binary.zip -d ./protoc &&
          set PATH="$PATH:$(pwd)/protoc/bin" &&
          chown -R $USER:$USER protoc &&
          rm protoc-27.1-osx-universal_binary.zip

      - name: Install protoc (windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/protocolbuffers/protobuf/releases/download/v27.1/protoc-27.1-win64.zip -OutFile protoc-27.1-win64.zip
          mkdir protoc
          Expand-Archive -Path protoc-27.1-win64.zip -DestinationPath protoc
          Get-Acl -Path protoc -Recurse
          Get-Acl -Path protoc -Recurse | Set-Acl -Path protoc
          Remove-Item protoc-27.1-win64.zip

      - uses: actions-rs/cargo@v1.0.1
        env: 
          PROTOC: ${{ env.PROTOC }}
        name: cargo test --verbose
        with:
          command: test
          args: --verbose
